# -*- coding: utf-8 -*-
"""45.3 NLP-Part 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1natffjdJddxXWpoPsYorfr3CFsUkSBnD

#Natural Language Processing
- Basic Text Processing Part 2

- How to remove punctuation - !"#&$@<>+=/.,`[]{}()~

- How to remove Stopwords - "a","the","while" some example of stop words
"""

var = "My name is Dipak and i live in Pune$"

import string

print(dir(string))

print(string.punctuation)

punch = set(string.punctuation)
print(punch)

Var = "My name is Dipak and i live in Pune$"

for i in punch:
  if i in var:
    var  = var.replace(i,"")

print(var)

"""## STOPWORDS CLEANING
- words which do not contain any useful information
- Hi I am and my name is Dipak
- Dipak
- English how many words are there
- NLTK - module in python which have a predefine Stopwords list
"""

words = ["a","an","we"]
# we are taking 3 words as stopwords
sent = "an apple fell on person head we"

for j in words:
  if j in sent:
    sent = sent.replace(j,"")

print(sent)

sent = sent.split(" ")
print(sent)

new_sent = ""
for i in sent:
  if i not in words:
    new_sent = new_sent+" "+i

print(new_sent)

"""#45.4 NLP-Part 4

#45.5 NLP-Part 5

# Seech to Text Recognition
- SpeechRecognition
- pyaudio
"""

!pip install SpeechRecognition

!pip install PyAudio

import speech_recognition as sr
r = sr.Recognizer()
with sr.Microphone() as source:
  print("system listen")
  Audio = r.listen(source)
query = r.recognize_google(Audio,language = 'en-in')
print(query)

