# -*- coding: utf-8 -*-
"""All_Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vLkh0cBnfFaIQYZuCVVpPDoIm6Y6esoU

PANDAS
"""

import pandas as pd

s = pd.Series()
s

l = [10, 20, 30, 40, 50] # list
pd.Series(l)

## Using np array
import numpy as np
a = np.array(["a", "b", "c", "d",""])
b = ([10, 11, 12, 13, 14])
pd.Series(a, b)

# Adding labels in series
age = pd.Series([10, 11, 12], index = ["Sudiptha", "Akhila", "Rohit"])
age

import pandas as pd
my_set=[68,72,82,55,95]
df=pd.DataFrame(list(my_set),columns=['Weight'],index=['Shailesh','Sai','Harsha','Jagdeesh','Mujeeb'])
print(df)

from ast import Name
import pandas as ab
a_set = {10,20},{30,40}
a=ab.DataFrame(list (a_set),index=[['dipak','Sai'],['Jagdeesh','Mujeeb']])
print(a)

import pandas as ab

# Use a list instead of a set for ordered values
a_set = [10, 20, 30]
a = ab.DataFrame(a_set, columns=['Weight'], index=['dipak', 'Sai', 'Harsha'])

# Print the DataFrame with formatted output
print("Name     Weight")
for index, row in a.iterrows():
    print(f"{index: <8} {row['Weight']}")

import pandas as ab

# Define a list of tuples for the data
a_set = {10, 20,30, 40}

# Create the DataFrame with a single index for the rows
index = ['dipak', 'Sai', 'Jagdeesh', 'Mujeeb']

# Create the DataFrame from the data and set the index
a = ab.DataFrame(a_set, columns=[0], index=index)

# Print the DataFrame
print(a)

import pandas as ab

# Create the data as a list of values
data = ([10, 20], [30, 40])

# Define the index
index = ['dipak', 'Sai', 'Jagdeesh', 'Mujeeb']

# Create the DataFrame
a = ab.DataFrame(data, columns=[0], index=index)

# Print the DataFrame
print(a)

import pandas as ab

# Define the data as a list of tuples
a_set = [(10, 20), (30, 40)]

# Flatten the data into a single list
flattened_data = [item for sublist in a_set for item in sublist]

# Define the index
index = ['dipak', 'Sai', 'Jagdeesh', 'Mujeeb']

# Create the DataFrame
a = ab.DataFrame(flattened_data, columns=[0], index=index)

# Print the DataFrame
print(a)

import pandas as pd
data={'name':['Sam','Arvind','Sai'],'Percentage':[90,95,85],'ID':[1,2,3]}
df=pd.DataFrame(data,index=[1,2,4])
print(df)

l = [10, 20, 30]
s = pd.Series(l, index = [0, 1,2])
print(s)

import pandas as pd
import numpy as np

a=np.array([10,20,30,40])
s=pd.Series(a,index=['A','B','C','D'])
print(s)
print(s.shape)
print(s.size)
print(s.memory_usage())
print(s.ndim)
print(type(a))

###Commited
'''import pandas as pd

df1=pd.DataFrame({'Player':['Player1','Player2','Player3','Player4'],
                  'Scores':[88,92,63,22]})

df2=pd.DataFrame({'Player':['Player1','Player2','Player4'],
                  'Wickets':[0,1,5]})

df3=pd.DataFrame({'Player':['Player4','Player2','Player3'],
                  'Catch' :[0,2,1]})

df4=pd.DataFrame({'Player':['Player4','Player5','Player3'],
                  'Fifty' :[0,2,1]})

print(df1)
print(' ')
print(df2)
print(' ')
print(df3)
print(' ')
print(df4)
print(' ')
merged_df = pd.merge(pd.merge(pd.merge(df1, df2, on='Player', how='outer'), df3, on='Player', how='outer'), df4, on='Player', how='outer')
print(merged_df)'''

import pandas as pd

df1= pd.DataFrame({'Player':['Player1','Player2','Player3','Player4'],
                   'Score':[10,20,30,50]})

df2= pd.DataFrame({'Player':['Player1','Player2','Player4'],
                   'wickets':[0,3,1]})
df3=pd.DataFrame({'Player':['player4','Player3','Player1'],
                  'Catch':[0,2,1]})

print(df1)
print('')
print(df2)
print('')
print(df3)
print('')
merged_df = pd.merge(pd.merge(pd.merge(df1, df2, on='Player', how='outer'), df3, on='Player', how='outer'), df4, on='Player', how='outer')
print(merged_df)

import pandas as pd
df3=pd.DataFrame({'Key':['A','B','C','D'],
                  'Value':[1,2,3,5]})

df4=pd.DataFrame({'Key':['B','D','E','F'],
                  'Value':[5,6,7,5]})

df3

df4

import pandas as pd

merged_df1 = pd.merge(df3, df4, on='Key', how='left')
print(merged_df1)

import pandas as pd

# Create the first DataFrame
df3 = pd.DataFrame({'Key': ['A', 'B', 'C', 'D'],
                    'Value': [1, 2, 3, 5]})

# Create the second DataFrame
df4 = pd.DataFrame({'Key': ['B', 'D', 'E', 'F'],
                    'Value': [5, 6, 7, 5]})

# Merge the DataFrames on the correct column name
merged_df1 = pd.merge(df3, df4, on='Key', how='left')
print(merged_df1)

merged_df1= pd.merge(df3, df4, on='Key', how='right')
print(merged_df1)

#Create two pandas series and perform floordivision and check if series one is greater than or equal to another series or not.

import pandas as pd
s1 = pd.Series([10, 20, 30, 40, 25])
s2 = pd.Series([5, 10, 15, 20, 50])
s3=s1.floordiv(s2)    #s3=s1//s2
print(f's3 = \n {s3}')
s4=s1>=s2
print(f's4 = \n {s4}')

a = pd.Series((1, 2, 3, 4, 100))
b = pd.Series([10, 20, 30, 40, 100])
b.le(a)

"""Numpy"""

import numpy as np

a = np.array([[1, 2, 3]])
print(a)
print(a.T) # T is used to transpose the vector

# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3],[7, 5, 8]])

# Transpose the matrix
transposed_matrix = matrix.T

print("Original matrix:\n", matrix)
print("Transposed matrix:\n", transposed_matrix)

a = np.array([[1, 6, 7],
              [4, 3, 9]])
print(a)

# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.min(a,axis=1))
print('Mean :',np.min(a,axis=0))
print('Mean :',np.mean(a,axis=1))
print('Median :',np.median(a,axis=1))
print('Median :',np.median(a,axis=0))

