# -*- coding: utf-8 -*-
"""GenAi-Day_01-ASEML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3Qtia6501Xhdhl9K98b8nIFiOuJ05Xh
"""

from google.colab import userdata
api_key=userdata.get("openai_key")

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# pip install openai

from openai import OpenAI
client = OpenAI(api_key=api_key)

completion = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {"role":"system","content":"You are a poetic assistant, describe everything asked in a funny way."},
        {"role":"user","content":"Compose a poem that explains RCP's poor performance on IPL."}
        ]
)

!pip install openai

!pip install openai

import openai
from google.colab import userdata

# Retrieve the API key securely
api_key = userdata.get("openai_key")
openai.api_key = api_key

# Request to the API
try:
    completion = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are a poetic assistant, describe everything asked in a funny way."},
            {"role": "user", "content": "Compose a poem that explains RCP's poor performance on IPL."}
        ]
    )
    print(completion.choices[0].message['content'])
except openai.error.RateLimitError as e:
    print("Rate limit exceeded. Please check your quota or try again later.")
except openai.error.AuthenticationError as e:
    print("Authentication error. Please check your API key.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

#Using Gemini Key

from google.colab import userdata
gemini_api=userdata.get('Gemini_key')

!pip install google-generativeai

from google import generativeai as genai

genai.configure(api_key=gemini_api)

for model in genai.list_models():
  print(model)

for model in genai.list_models():
    if "generateContent" in model.supported_generation_methods():
        print(model)

for model in genai.list_models():
    print(model.supported_generation_methods)  # Check if it's a list

for model in genai.list_models():
    if "generateContent" in model.supported_generation_methods:
        print(model)

# text - text
#image - text
t2t_model=genai.GenerativeModel(model_name="gemma-3-1b-it")

#t2t_model.generate_content("What is encoder and decoder architecture?")
t2t_model.generate_content("What is SQL").text

"""# New Section"""

from google.colab import drive
drive.mount('/content/drive')

#Image to text
gemini_image_description=genai.GenerativeModel(model_name="gemini-1.5-pro-latest")

import PIL.Image

image=PIL.Image.open("Cat.jfif")

gemini_image_description.generate_content(["Tell this image indicate which animal",image]).text

image

#Word Embeddings

corpus = [
    'Text of the first document.'
    'Text of second document made longer'
    'Number three'
    'This number four'
]

!pip install gensim

#!pip install numpy==1.26.4
print(np.__version__)

import gensim
from gensim.utils import simple_preprocess
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

!apt update
!apt install -y python3-numpy

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip -q install langchain
# !pip install pypdf
# !pip install sentence-transformers==2.2.2

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install openai
# !pip install tiktoken
# !pip install faiss-cpu

!pip install -U langchain-community

!mkdir pdfs

#from langchain.document_loaders import PyPDFDirectoryLoader
from langchain_community.document_loaders import PyPDFDirectoryLoader

loader=PyPDFDirectoryLoader("pdfs")

data=loader.load()

data

from langchain.text_splitter import RecursiveCharacterTextSplitter

splitter=RecursiveCharacterTextSplitter(chunk_size=500,chunk_overlap=20)

chunks=splitter.split_documents(data)

len(chunks)

!pip install -U langchain-huggingface

!pip install sentence-transformers

from langchain.embeddings import HuggingFaceEmbeddings

#embeddings=HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

#from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

!pip install numpy==1.26.4

!pip install -U langchain langchain-community langchain-huggingface sentence-transformers transformers

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

from langchain.vectorstores import FAISS

vectordatabases=FAISS.from_documents(chunks,embeddings)

query="what is the phone number?"

vectordatabases.similarity_search(query,top_k=2)

from google.colab import userdata
gemini_api=userdata.get('Gemini_key')


from langchain.chat_models import ChatOpenAI

# Initialize the OpenAI LLM (this would be the `llm` you pass into `RetrievalQA`)
llm = ChatOpenAI(openai_api_key=api_key)

from langchain.chains import RetrievalQA

# Assuming `vectordatabases` is your retriever object
result = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vectordatabases.as_retriever()
)

response = result.run(query)

from langchain.llms import openai

from google.colab import userdata
api_key = userdata.get("openai_key")

llm=openai.api_key = api_key

from langchain.chains import RetrievalQA

result=RetrievalQA.from_chain_type(llm=llm,chain_type="stuff",retriever=vectordatabases.as_retriever())

!pip install google-generativeai langchain

!pip install google-generativeai langchain

import google.generativeai as gemini
from langchain.schema import BaseLLM
from langchain.chat_models import ChatOpenAI  # You can compare this format with OpenAI

# Custom wrapper for Google Gemini
class ChatGoogleGemini(BaseLLM):
    def __init__(self, api_key):
        self.api_key = api_key
        gemini.configure(api_key=self.api_key)

    def _call(self, prompt: str) -> str:
        # Use Google's Generative AI API to generate text from prompt
        response = gemini.generate_text(prompt=prompt)
        return response.text

# Now, initialize the LLM (Language Model)
llm = ChatGoogleGemini(api_key="gemini_api")

from langchain.chains import RetrievalQA

# Assuming vectordatabases is a pre-built retriever (e.g., FAISS, Chroma)
result = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",  # or other available chain types like "map_reduce", etc.
    retriever=vectordatabases.as_retriever()
)

# Now you can query using the result
response = result.run(query)
print(response)

from langchain.chat_models import ChatGoogleGemini  # Hypothetical class, update with real class if available
from langchain.chains import RetrievalQA
import google.generativeai as gemini  # Assuming Gemini API wrapper is available

# Authenticate with the Google Gemini API (ensure authentication is set up correctly)
gemini.configure(api_key=gemini_api)


# Initialize Gemini LLM (you might have to implement a custom wrapper class for LangChain if not available)
class ChatGoogleGemini:
    def __init__(self, api_key):
        self.api_key = api_key
        self.client = gemini.Client(api_key=self.api_key)

    def complete(self, prompt):
        response = self.client.generate_text(prompt=prompt)
        return response.text

# Initialize Gemini LLM (this would be the `llm` you pass into `RetrievalQA`)
llm = ChatGoogleGemini(api_key=gemini_api)

# Assuming vectordatabases is a pre-built retriever (like FAISS, Chroma, etc.)
result = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",  # or other available chain types (stuff, map_reduce, etc.)
    retriever=vectordatabases.as_retriever()
)

# Now you can query using the result
response = result.run(query)
print(response)

!pip install openpyxl

import pandas as pd

path="/content/sample_data/california_housing_train.csv"
df=pd.read_csv(path)
df.head(5)

import pandas as pd

# Step 1: Read the existing data
path = "/content/sample_data/california_housing_train.csv"
df = pd.read_csv(path)

# Step 2: Create two new sample rows (must match the columns)
new_data = pd.DataFrame([
    {
        'longitude': -120.0,
        'latitude': 35.0,
        'housing_median_age': 18.0,
        'total_rooms': 1000.0,
        'total_bedrooms': 200.0,
        'population': 500.0,
        'households': 180.0,
        'median_income': 2.5,
        'median_house_value': 90000.0
    },
    {
        'longitude': -121.5,
        'latitude': 36.1,
        'housing_median_age': 22.0,
        'total_rooms': 1200.0,
        'total_bedrooms': 250.0,
        'population': 600.0,
        'households': 210.0,
        'median_income': 3.1,
        'median_house_value': 110000.0
    }
])

# Step 3: Append the new rows to the CSV
new_data.to_csv(path, mode='a', index=False, header=False)

print(" 2 new rows appended to the CSV file.")

df_updated = pd.read_csv(path)
df_updated.tail(5)

"""#Sentiment Analysis"""

# customer feedback- I hate your service. I enjoy the service that you provide

#Integrate huggingface with colab

!huggingface-cli login

# transformer pipeline

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# pip install transformers

from transformers import pipeline

llm=pipeline(task="sentiment-analysis")

llm("I am learning GenAI and it looks good but hard to learn to me.")[0]["label"]

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# pip install gradio

def sentiment_analysis(text):
  return llm(text)[0]["label"]

import gradio as gr

