# -*- coding: utf-8 -*-
"""GenAI_Day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dN5J73wr7oembrQBHE2yVE9ipaIsq-mf

# Sentiment Analysis
"""

#Integrate Hugging Face with colab

!huggingface-cli login

#Transformer pipeline

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# pip install transformers

from transformers import pipeline

llm=pipeline(task="sentiment-analysis")

llm("I am learning GenAI and it is fascinating")[0] ["label"]

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# pip install gradio

def sentiment_analysis(text):
  return llm(text)[0]["label"]

import gradio as gr

demo=gr.Interface(fn=sentiment_analysis,inputs="text",outputs="text",title="Sentiment_analysis_gradio_application")

demo.launch()

text_list=["How bad are you?",
           "Thank you for visiting",
           "Not great but thanks",
           "Thanks but not good"]

llm=pipeline(task="sentiment-analysis",model="distilbert/distilbert-base-uncased-finetuned-sst-2-english")

llm(text_list)

"""# **Text Classification**"""

from transformers import pipeline

classifier = pipeline(task="text-classification", model="SamLowe/roberta-base-go_emotions", top_k=None)

sentences = ["I am learning GenAI"]

classifier(sentences)
#print(model_outputs[0])
# produces a list of dicts for each of the labels

classifier(sentences)

classifier(sentences)[0]



"""#Summerization"""

from transformers import pipeline

# Correct the task name from "Summerization" to "summarization"
summerizer = pipeline(task="summarization", model="sanjayuzu/facebook-bart-large-cnn-pretrained_text_summarization_samsum", top_k=None)

article="""Dr. Kalam was born on October 15, 1931, in the small town of Rameswaram, Tamil Nadu, into a poor but religious family. His father, Jainulabdeen, was a boat owner and a generous man, and his mother, Ashiamma, was a homemaker. Despite financial constraints, Kalam’s parents instilled in him the values of hard work, discipline, and a deep love for learning."""



print(summerizer(article,max_length=20,min_length=10)[0]["summary_text"])

text = """Amazon is the place where you can be a little crazy, a little quirky, and still do amazing things.— Anonymous.When you’re a startup, you have the advantage of being nimble. Use that to your advantage.— Jeff Bezos"""

#ner
#hindi
#q and answers

ner=pipeline("ner",aggregation_strategy="simple")

import pandas as pd
pd.DataFrame(ner(text))



"""#Translation From english to hindi"""

translator=pipeline("translation_en_to_hi",model="Helsinki-NLP/opus-mt-en-hi")

print(translator(text)[0]["translation_text"])

"""#Question and Answering"""

qabot=pipeline("question-answering")
question="what did the customer order?"
qabot(question=question,context=text)

question="who is the article about?"
print(qabot(question=question,context=text))

"""#Vanila Chatbot"""



chatbot=pipeline(model="facebook/blenderbot-400M-distill")

chatbot("Hi, How is the India country is?")

chatbot("where are you from?")

pip install gradio

import gradio as gr

def vanila_chatbot(message,history):
  return chatbot(message)[0]["generated_text"]

demobot=gr.ChatInterface(vanila_chatbot,title="vanila chatbot")

demobot.launch()

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip -q install langchain
# !pip -q install bitsandbytes accelerate transformers
# !pip -q install sentence_transformers
#

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip -q install unstructured
# !pip install faiss-cpu

!huggingface-cli login



# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -U langchain-community

from langchain_community.embeddings import HuggingFaceEmbeddings

from langchain.vectorstores import FAISS #database
from langchain.embeddings import HuggingFaceBgeEmbeddings #this is to create embeddings with a embedding model
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.document_loaders import UnstructuredURLLoader

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# pip install numpy==1.24.4

URLS=["https://www.cybage.com/"]

# extract the data for the URL
loaders=UnstructuredURLLoader(urls=URLS)

data=loaders.load()

#data

text_chunks=RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=200)

chunks=text_chunks.split_documents(data)

chunks[0]

len(chunks)

!pip install --force-reinstall --no-cache-dir numpy transformers

!pip install -U langchain langchain-community sentence-transformers

from langchain_community.embeddings import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

from langchain.vectorstores import FAISS

vectordatabase=FAISS.from_documents(chunks,embeddings)

vectordatabase

model="google/flan-t5-large"

from transformers import AutoTokenizer,AutoModelForSeq2SeqLM,pipeline
from langchain import HuggingFacePipeline

tokenizer1=AutoTokenizer.from_pretrained(model) # to generate tokens
model1=AutoModelForSeq2SeqLM.from_pretrained(model)
pipe=pipeline("text2text-generation",model=model1,tokenizer=tokenizer1)

!pip install -U langchain-huggingface

from langchain_huggingface import HuggingFacePipeline

llm=HuggingFacePipeline(pipeline=pipe,model_kwargs={"temperature":0.5,"max_length":1000})

from langchain.chains import RetrievalQA

from langchain.prompts import PromptTemplate
template="""use the context to provide a concise answer and if you don't know just say don't now.
{context}
Question: {question}
Helpful Answer:"""

prompt_template=PromptTemplate.from_template(template)

qa_chain=RetrievalQA.from_chain_type(llm,chain_type="stuff",retriever=vectordatabase.as_retriever(),chain_type_kwargs={"prompt":prompt_template})

question="who is the CEO of company?"
result=qa_chain({"query":question})

result

question="Is it a recruitment consultancy or a company?"
result=qa_chain({"query":question})

result["result"]

question="How many department they have?"
result=qa_chain({"query":question})

result["result"]

question="what is the phone number?"
result=qa_chain({"query":question})

result["result"]

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# pip install gradio

import gradio as gr

def fetech(question,history):
  result=qa=_chain({"query":question})
  return result["result"]

def fetech(question,history):
    result = qa_chain({"query": question})
    return result['result']  # or customize based on actual chain output

import gradio as gr

gr.ChatInterface(
    fn=fetech,  # <-- your function must be defined above
    chatbot=gr.Chatbot(height=300, type="messages"),
    textbox=gr.Textbox(
        placeholder="Ask me a yes or no question",
        container=False,
        scale=7
    ),
    title="Chat with website",
    description="Ask the chatbot any question",
    theme="soft",
    examples=["contact details", "Company CEO", "Department information"],
    cache_examples=True,
).launch(share=True)

