# -*- coding: utf-8 -*-
"""Python201_class_notes_5_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tIUteptu51P_XWQAaggXiLaLI71_yay2

## Pandas: Module
1. High performance data analysis.
2. Handles large data sets.
3. Supports different file formats.
4. More flexible.
5. Tabular format data (Rows and columns).
6. Efficient for missing data.
7. Supports Indexing, slicing, subset on large data sets.
8. Merge and join different data sets.
9. Reshape data sets.
<br>

Link: https://pandas.pydata.org/

- In general when we deal with data pandas libray is used very commonly due to some important functions in data science
    - data analysis
    - data cleaning
    - data exploration
    - data manipulation
    
- Pandas - Panel Data and python data analysis it's a multidimensional data involving measurements over time
- Pandas alone cannot perform. It is built on numPy, as it can also handle ndimensional array. So both libraries required
<br>
- Features - series obj & data frame,aligns data, slicing, indexing, subseting, handles missing data, groups by functionality
- Features - merging & joining, labeling of axes hierarchially, time-series functionality, reshaping & robust input/output tool
<br>
- Pandas - great for > 500k rows, works great for tabular data, arbitrary matrix & time series matrix
- Numpy - < 500k rows, however memory efficinet
"""

from google.colab import drive
drive.mount('/content/drive')

# Installing pandas
# pip install pandas

"""## Pandas: Three data structures
1. Series: 1-D (List)
2. Dataframe: 2-D (List or Dictionary or series)
3. Panel: Multi-Dimensional (data, major axis, minor axis)

### Series

Syntax:

```
import pandas as pd
pd.Series(data, index)
```
"""

import pandas as pd
pd.DataFrame(data)

"""### DataFrame:

Syntax:


```
import pandas as pd
pd.DataFrame(data)
```

### Panel:

Syntax:


```
import pandas as pd
pd.Panel(data, major axis, minor axis)
```

### DataFrame is the **most efficient data structure.**

## Series

1. Empty series
2. Using arrays
3. Using Lists
4. Using dictionary
5. Using tuple
"""

import pandas as pd

# Empty series
s = pd.Series()

l = [10, 20, 30, 40, 50] # list
pd.Series(l)

## Using np array
import numpy as np
a = np.array(["a", "b", "c", "d", "e"])
b = [10, 11, 12, 13, 14]
pd.Series(a, b)

l = (10, 20, 30, 40, 50) # using tuple
index = [-1, -2, -3, -4, -5]
pd.Series(l, index)

l = [10, 20, 30, 40, 50]
index = ['i', 'ii', 'iii', 'iv', 'v']
pd.Series(l, index)

# Adding labels in series
age = pd.Series(["A", "B", "C"], index = ["Sudiptha", "Akhila", "Rohit"])
age

"""## DataFrame"""

# creating a dataframe from a list
data = [12,22,33,44]
df = pd.DataFrame(data)
df

# adding index and column name
data = [12,22,33,44]
df = pd.DataFrame(data, index = ["Shailesh", "Sai", "Harsha", "Jagdeesh"], columns = ['age'])
df

a = {"fruit": ["Apple", "Banana", "Cherry"], "price": [10, 20, 30]}
b = [5, 7, 0]
pd.DataFrame(a, b)

# Your explanation and codes here

"""## Series attributes
|S.no.|function|Syntx|Explanation|
|---|---|---|---|
|1.| index| Series.index| Return all the index values.|
|2.| array| Series.array| Return array of values.|
|3.| values| Series.values| Return values of series.|
|4.| name| Series.name| Returns the name of a series.|
|5.| shape| Series.shape|shape of a series|
|6.| ndim| Series.ndim|dimension of a series|
|7.| size| Series.size|size of a series|
|8.| nbytes| Series.nbytes| Memory occupied by the values.|
|9.| memory usage|Series.memory_usage()| Memory occupied by both index and values.|
|10.| empty|Series.empty| Returns True if series is empty, else false|

### Index
"""

a = [1, 2, 3, 4, 5]
index = ["a", "b", "c", "d", "e"]
b = pd.Series(a, index)

b.index

"""### array"""

c = b.array
print(c)

c.to_numpy()

c = b.to_numpy()
print(c)

"""### Values"""

type(b.values)

b.values

"""### name"""

b.name

b = pd.Series([4, 6, 8, 10, 12], name = "Even")
b.name

"""### dtypes"""

b.dtype

"""### shape"""

b.shape

"""### ndim"""

b.ndim

"""### size"""

b.size

"""### empty"""

b.empty

pd.Series().empty # creating an empty series

"""### nbytes"""

b = pd.Series(0, [5])
b.nbytes

"""### memory usage"""

b = pd.Series(0, [5])
b.memory_usage()

b = pd.Series([0, 1], [5, 10])
print(b)
b.memory_usage()

b = pd.Series([0, 1, 2, 3, 4], ["a", "b", "c", "d", "e"])
b.memory_usage()

"""## Data frame

### Merging two data frames
Merging two data frames in pandas can be done using the merge() function. The merge() function allows you to combine two data frames based on one or more common columns. Here's an example.

Basic syntax:
<br>
**result = pd.merge(df1, df2, how='inner', on='common_column')**
<br>
where:
<br>
<br>
df1 and df2 are the dataframes you want to join.
<br>
<br>
**how** parameter specifies the type of join you want to perform. You can use 'inner', 'outer', 'left' or 'right'.
<br>
<br>
**on** parameter specifies the common column(s) that you want to join on.
"""

df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'],
                    'value': [1, 2, 3, 4]})

df2 = pd.DataFrame({'key': ['B', 'D', 'E', 'F'],
                    'value': [5, 6, 7, 8]})

merged_df = pd.merge(df1, df2, on='key') # Here only key column matches.
print(merged_df)

"""### Outer merge"""

merged_df = pd.merge(df1, df2, on='key', how='outer') # outer includes all rows from both df1 and df2, with NaN values in any columns where data is missing.
print(merged_df)

"""### Inner merge"""

merged_df = pd.merge(df1, df2, on='key', how='inner') # inner includes only key column matches.
print(merged_df)

"""### Left join"""

merged_df = pd.merge(df1, df2, on='key', how='left') # left means your first datafrmae will be main and merging will be based on first dataframe
print(merged_df)

"""### Right join"""

merged_df = pd.merge(df1, df2, on='key', how='right') # right means your second datafrmae will be main and merging will be based on second dataframe
print(merged_df)

"""### Check if two data frames are same or not using equals function
- If same, output will be true else false
"""

df1['key'].equals(df2['key'])

"""### Join two dataframes
Pandas join function is used to join two or more dataframes based on their index or column values. It works similarly to the SQL JOIN statement, allowing you to combine data from different sources into a single dataframe.
<br>
<br>
The basic syntax of the join function is as follows:
<br>
<br>
**df.join(other, on=None, how='left')**
<br>
<br>

where:
<br>
<br>
**df**: the dataframe you want to join with another dataframe.
<br>
<br>
**other**: the other dataframe you want to join with df.
<br>
<br>
**on**: the column or index level names to join on. If not specified, the join will be based on the index of other dataframe.
<br>
<br>
**how**: the type of join to be performed, which can be **left**, **right**, **outer**, or **inner**. **By default, 'left' join is performed**.
"""

# create two sample dataframes
df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'], 'value1': [1, 2, 3, 4]})
df2 = pd.DataFrame({'key': ['B', 'D', 'E', 'F'], 'value2': [5, 6, 7, 8]})
print(df1)
print(df2)
# join df1 and df2 on their common index
result = df1.join(df2.set_index('key'), on='key')

print(result)

"""#### Difference between merge and join

Merge is used to combine data frames based on the values of common columns, while join is used to combine data frames based on their indexes. We can also specify the type of join (inner, left, right, or outer) using the how parameter.

### Join multiple dataframes
"""

### merging multiple dataframes
player = ['Player1','Player2','Player3', 'Player4']
score = [88,92,63, 22]
df1 = pd.DataFrame({'Player':player, 'Scores': score})
print(df1)

player = ['Player1','Player2','Player4']
wicket = [0,1,5]
df2 = pd.DataFrame({'Player':player, 'Wickets': wicket})
print(df2)

player = ['Player4','Player2','Player3']
catches = [0, 2, 1]
df3 = pd.DataFrame({'Player':player, 'Catch': catches})
print(df3)

player = ['Player4','Player5','Player3']
fifty = [0, 2, 1]
df4 = pd.DataFrame({'Player':player, 'Fifty': fifty})
print(df4)

# Merge df1 and df2 on 'Player' column
df_merged = pd.merge(df1, df2, on='Player', how='outer')

# Merge df_merged and df3 on 'Player' column
df_merged = pd.merge(df_merged, df3, on='Player', how='outer')

# Merge df_merged and df4 on 'Player' column
df_merged = pd.merge(df_merged, df4, on='Player', how='outer')

print(df_merged)

"""### Basic mathematical operations

|S.no.|Operations|Method 1|Method 2|Explanation|
|---|---|---|---|---|
|1| addition|a + b|a.add(b)|Addition|
|2| substract|a - b|a.subtract(b)|Subtraction|
|3| multiply|a * b|a.multiply(b)|Multiplication|
|4| division|a / b|a.divide(b)|Division|
|5| modulo|b%a|a.mod(b)|remainder|
|6| power|a ** b|a.pow(b)|raises each value in the DataFrame a specified number of times|
|7| less than|b < a|b.lt(a)|less than|
|8| greater than|b > a|b.gt(a)|greater than|
|9| equal to|b == a|b.eq(a)/b.equals(a)|compare if they are equal or not|
|10|less than equal to|b <= a|b.le(a)| lesss than or equal to|
"""

a = pd.Series((1, 2, 3, 4, 5))
b = pd.Series([10, 20, 30, 40, 50])
a + b

a.add(b)

a

b

a.subtract(b)

a.multiply(b)

a.divide(b)

a.mod(b)

a.floordiv(b)

b.pow(a)

b.lt(a)

a = pd.Series((1, 2, 3, 4, 100))
b = pd.Series([10, 20, 30, 40, 100])
b.le(a)

b.lt(a)

b.ge(a)

b.gt(a)

b.eq(a)

b.equals(a)

b ** a

b.pow(a)

2 ** 2

"""## Importing and analysis of a file

## DataFrame
* Accessing / slicing
1. head()
2. tail()
3. describe(): Only for numerical columns
4. shape: Attribute
5. Slicing: [start: stop: step] - rows
6. slicing: columns ["column_name"]
"""

# importing file from a local folder
from google.colab import files
uploaded = files.upload()

cars = pd.read_csv("mtcars.csv") # read Crop data files
#print output
cars

#to check the type of data provided
type(cars)

"""### Basic data exploration using pandas
|S.no.|Function|Explanation|
|---|---|---|
|1|df.head()|examine first five observation we can assign more values in bracket too|
|2|df.tail()|examine last five observation we can assign more values in bracket too|
|3|df.shape|check the no of rows & columns in a data frame|
|4|df.dtypes| # to check just the datatypes of columns
|5|df.info()|dataframe, index dtype and column dtypes, non-null values and memory usage|
|6|df.drop(columns=['C1', 'C2'])| drop unwanted column|
|7|df.sort_values("C1",ascending = False)|Sorting values|
|8|df['C1'].unique()|All unique values|
|9|df['C1'].nunique()|Number of unique values|
|10|df.isnull()|Identify null values, Null values will be true|
|11|df.fillna(df["C1"].median())|fill the missing values in the df columns|
|12|df.describe()|Summary statistics|
|13|df.rename(columns={'given_name' : 'replacement'})|rename columns|
|14|df['C1].sum()|Addition|
|15|df.C1.map|map catgory into number or vice versa|
|16|df.loc()|splicing columns based on label|
|17|df.iloc()|splicing columns based on index|
|18|df.group_by()|grouping categories and performing some maths|
|19|df.dropna()|Will drop complete row if there is any na|
|20|df.fillna()|fill missing values|
|21|df.replace()|help in encoding|
|22|df.drop_duplicates()|dropping duplicates|

"""

#to read the first 5 records
cars.head()

#to read last 5 records
cars.tail()

# to check the no of rows & columns in a data frame
cars.shape

cars.info()

# drop unwanted column
cars_drop = cars.drop(columns=['vs', 'qsec'])
cars_drop.head()

## Renaming columns
cars=cars.rename(columns={'disp' : 'displacement'})
cars.head()

## mapping am columns
# Be sure about column names before doing any changes
cars['am'] = cars['am'].map({0: 'automatic',  1: 'manual'})
cars.head()

# encoding categorical variable
cars['vs'].replace([0, 1], ['V_shape', 'Straight_line'])
cars

## Missing value
cars.isnull()

## Missing value
cars.isnull().sum()

# Your code here

"""### Basic statistical analysis"""

# basic statistical analysis
# cars.mean()
# cars.median()
# cars.mode()
# cars.std()
# cars.max()
# car.var()
# cars.min()
# cars.count()
cars.describe(include = "all")

# basic statistical analysis
# cars.mean()
# cars.median()
# cars.mode()
# cars.std()
# cars.max()
# car.var()
cars['mpg'].min()
cars.mpg.count()

"""### loc vs iloc

The Pandas offers .loc[] and .iloc[] methods for data slicing.

- The **.loc[] method is a label based method** that means it takes names or labels of the index when taking the slices,
- **.iloc[] method is based on the index's position**. It behaves like a regular slicing where we just have to indicate the positional index number and simply get the appropriate slice.

### iloc
"""

#to view entire row & 4th column from DS [: is the row, 4 is the column no]
#we are viewing hp coulmn only
cars.iloc[:,4]

cars.iloc[0:5,4]

"""### loc"""

# read data set and store it in data frame
#see all record of mpg column
only_mpg = cars.loc[:,"mpg"]
only_mpg

#display records from index 0 to index 6 from mpg columns
cars.loc[:6,"mpg"]

#see 1st 7 records from mpg to qsec column
cars.loc[:6,"mpg":"qsec"]

# Your code here

"""### Group by"""

#group by
group_by_am = cars.groupby('am')
group_by_am.size() # how many elements are present in each group

#group by

group_by_m = cars.groupby(['am', "gear"])
group_by_m.size() # how many elements are present in each group

"""### Filter columns"""

## Filter records of having 8 cylinder
cars_8_cyl = cars[cars['cyl'] > 6]
cars_8_cyl

## Filter records
cars_6_cyl = cars[cars['cyl'] > 6]
cars_6_cyl

# minimum mileage of 4 cylinder car
cars_4cyl = cars[cars.cyl == 4]
cars_4cyl[cars_4cyl.mpg == cars_4cyl.mpg.min()]

#cars_4cyl.mpg.min()

"""### Value_count"""

# value_count
# find the value counts
cars.am.value_counts()

cars['Type'].value_counts()

"""### Fill the missing values"""

## Filling missing values with a constant, here 0
## There is no missing value in this dataset
#fill_0 = cars.fillna(0)
# fill_0.head()

#fill_mean = cars.fillna(cars.mean()) # replacing all columns with mean
# fill_mean

#fill_mode = cars.fillna(cars.wt.mode()) # replacing all columns with mode
# fill_mode

"""### Creating a new column"""

# creating a new column
cars['Best'] = cars['mpg'] * cars['wt']
cars.head()

cars['kpl'] = cars.apply(lambda mile: (mile.mpg * 0.43), axis = 1)
cars

## Unique values
cars.Type.unique()

cars.Type.nunique()

## duplicate value
cars.drop_duplicates(inplace=True)

df1 = cars.sort_values("mpg", ascending = False)

"""### Saving cleaned file

"""

# Saving final file
cars.to_csv("mtcars_cleaned.csv",index=False,header=True)

cars.to_excel("mtcars_cleaned.xlsx",index=False,header=True)