# -*- coding: utf-8 -*-
"""Python _Introduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4gO3d6HtRiCweVnmZOAWM5wQtRdXRh0
"""

##interactive py NB

print("hi all")

a = int(input("enter a"))
b = int(input("enter b"))

print(a + b)

#

b1 = "Python"
b2 = "Programming"

print (b1 + b2)

ans = b * a
print(ans)

name = input("Enter your name")
print ("Hello", name , "congratualation!")

from __future__ import division
## WAP to prompt user to enter 2 number and print the questient.

divident = int(input("Enter the divident:"))
divsor = int(input("Enter the divsor:"))

quotient = divident / divsor
print ("Quostent is:",quotient)

c = " "
 print(a)

print("""
hi
There
""")

b = True
 print(B)

a= 5
type (a)

type (b)
type (c)

a1 = 0
print(not a1)

a2 = 10

print(not a2)

##Tuple

virat_score = [{34, 56}, {76, 32, 20, 98}]
virat_score

type(virat_score)

virat_score = list(virat_score)
virat_score



import random
list1= []
for _ in range(5) :
  r = random.randint(1, 10)
  list1.append(r)

  list1

new_list = list(range(10))
new_list

my_tuple = (1, 2, 3, "apple", "banana")

my_tuple[1] = 5  # This will raise a TypeError

tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)

# Concatenating the tuples
result = tuple1 + tuple2
print(result)  # Output: (1, 2, 3, 4, 5, 6)

###SET
# Using curly braces
my_set = {1, 2, 3, "apple"}

# Using the set() function
another_set = set([1, 5, 2, 3, 4])  # Duplicates will be removed and maintain ordered indexing
print(another_set)  # Output: {1, 2, 3, 4}

##Dictonary
# Using curly braces
my_dict = {
    "name": "Alice",
    "age": 30,
    "city": "New York"
}

# Using the dict() function
another_dict = dict(name="Bob", age=25, city="Los Angeles")

my_dict["age"] = 31  # Update existing key
my_dict["country"] = "USA"  # Add new key-value pair

print(my_dict)

